#include "contiki-conf.h"

#ifdef SLEEP_CONF_POWER_CONFIG
#define SLEEP_POWER_CONFIG() SLEEP_CONF_POWER_CONFIG()
#else
#define SLEEP_POWER_CONFIG()
#endif

#ifdef SLEEP_CONF_POWER_CONFIG_RESUME
#define SLEEP_POWER_CONFIG_RESUME() SLEEP_CONF_POWER_CONFIG_RESUME()
#else
#define SLEEP_POWER_CONFIG_RESUME()
#endif

#ifdef LP_SLEEP_CONF_POWER_CONFIG
#define LP_SLEEP_POWER_CONFIG() LP_SLEEP_CONF_POWER_CONFIG()
#else
#define LP_SLEEP_POWER_CONFIG()
#endif

#ifdef LP_SLEEP_CONF_POWER_CONFIG_RESUME
#define LP_SLEEP_POWER_CONFIG_RESUME() LP_SLEEP_CONF_POWER_CONFIG_RESUME()
#else
#define LP_SLEEP_POWER_CONFIG_RESUME()
#endif

#ifdef STOP_CONF_POWER_CONFIG
#define STOP_POWER_CONFIG() STOP_CONF_POWER_CONFIG()
#else
#define STOP_POWER_CONFIG()
#endif

#ifdef STOP_CONF_POWER_CONFIG_RESUME
#define STOP_POWER_CONFIG_RESUME() STOP_CONF_POWER_CONFIG_RESUME()
#else
#define STOP_POWER_CONFIG_RESUME()
#endif



void MCU_Enter_LowPowerRunMode(void);
void MCU_Enter_LowPowerSleepMode(void);
void MCU_Enter_StopMode(void);
void MCU_Enter_StandbyMode(void);
void MCU_Enter_SleepMode(void);
